### ISSUE TITLE
Add the Azure CLI commands to configure the AI service

### ISSUE THREAD

**Issue by agoncal** [cescoffier/quarkus-llm-workshop#13]
In slot 1 we need the following properties:

```
quarkus.langchain4j.azure-openai.api-key=${AZURE_OPENAI_API_KEY}
quarkus.langchain4j.azure-openai.resource-name=redhat-workshop-aoai
quarkus.langchain4j.azure-openai.deployment-id=gpt-35-turbo
```

For people doing the workshop online, they need to create their own deployment, get their own key... It would be good to have a script with the Azure CLI command in Appendix that does that.

**Comment by cescoffier** [comment]
@agoncal definitely!

That being said, I never did it. For the event, Microsoft provides the service for us. That was great, and it worked wonderfully well!

That being said, I would be happy to learn how to do it.

**Comment by agoncal** [comment]
@cescoffier you can assign this issue to me

**Comment by agoncal** [comment]
Closed with https://github.com/cescoffier/quarkus-llm-workshop/pull/17
